version: "3"

services:
  rss-app:
    image: rss-db-app
    container_name: rss-app
    env_file: .env
    restart: always
    network_mode: bridge
    command: npm run start:dev

    build: 
      context: .
      dockerfile: Dockerfile
      target: development

    volumes: rss_app:/usr/src/app
    ports: "${PORT}:${PORT}"
    depends_on: rss-db

  rss-db:
    image: rss-db-image
    container_name: rss-db
    env_file: .env
    restart: always
    network_mode: bridge

    build: 
      context: .
    volumes: rss_data:/var/lib/postgresql/data
    environment:
      POSTGRES_DB: ${DB_NAME}
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
    ports: "${DB_PORT}:${DB_PORT}"

    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U habrpguser -d habrdb"]
      interval: 10s
      timeout: 5s
      retries: 5
      start_period: 10s

volumes:
  rss_app:
  rss_data: